routes/web.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BizController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ServiceController;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AddProductController;
use App\Http\Controllers\UpdateBusinessAdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

/*Route::get('/new_sign_up', function () {
    return view('new_signup_thank_you');
});*/

Route::get('/new_login', function () {
    return view('auth/new_login');
});

Route::get('/new_register', function () {
    return view('auth/new_register');
});
Route::get('/new_admin_register', function () {
    return view('admin/admin_registration');
});


Route::get('/biz-registration', function () {
    return view('new_create_business_profile');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::get('/admin/usermanagement',[UserController::class,'index'])->middleware('admin');

Route::get('/admin/businesses',[BizController::class,'list'])->middleware('admin');

Route::get('/admin/orders',[OrderController::class,'showAllOrders'])->middleware('admin');

Route::get('/admin/order/{id}',[OrderController::class,'showOrderLine'])->middleware('admin');
Route::get('/admin/order/delete/{id}',[OrderController::class,'deleteAdminOrder'])->middleware('admin');
Route::get('/admin/orders/delete/{id}',[OrderController::class,'deleteAdminOrders'])->middleware('admin');

//Route::view('/biz-registration', 'biz-registration')->middleware('auth:sanctum');
//Route::post('/biz-registration', [BizController::class,'save']);

Route::middleware(['auth:sanctum', 'verified'])->get('/sign-up-thank-you', function (){ return view('new_signup_thank_you'); })->name('signup-thanks');

Route::middleware(['auth:sanctum', 'verified'])->get('/contacts', [ContactController::class, 'show_contact'])->name('contact');

Route::post('contacts/add_contact', [ContactController::class,'addContact']);
Route::get('contacts/delete/{id}',[ContactController::class,'delete_contact']);

Route::get('business-contacts', [BizController::class,'show_BizContact']);
Route::get('business-owner-profile', [BizController::class,'business_owner_profile']);

Route::middleware(['auth:sanctum'])->post('business-contacts/add_bizcontact', [BizController::class,'addBizContact']);
Route::get('business-contacts/delete/{id}',[BizController::class,'delete_bizContact']);

Route::get('biz-profile/{id}', [BizController::class,'show_data']);
Route::post('biz-profile/{id}/add_product', [ProductController::class,'addData']);
Route::post('biz-profile/{id}/update_banner', [BizController::class,'updateBanner']);
Route::post('biz-profile/{id}/update_logo', [BizController::class,'updateLogo']);
Route::post('biz-profile/{id}/add_service', [ServiceController::class,'save_service']);

Route::post('biz-profile/{id}/add_photo', [BizController::class,'addPhoto']);

Route::match(['get','post'],'/cart/add-item', [CartController::class,'addItem'])->name('become-a-customer');
Route::post('/cart/update_quantity', [CartController::class,'updateQuantity']);
Route::post('biz-profile/{id}/add_tags', [BizController::class,'addCategoryTags']);
Route::get('/biz-profile/{business_id}/remove-tag/{category_tag}', [BizController::class, 'removeCategoryTag']);

Route::middleware(['auth:sanctum', 'verified'])->get('/business-contacts', function () {
    return view('business-contacts');
})->name('business-contacts');

Route::middleware(['auth:sanctum', 'verified'])->get('/purchase-history', function () {
    return view('purchase-history');
})->name('purchase-history');

/*Route::middleware(['auth:sanctum', 'verified'])->get('/posts', function () {
    return view('posts');
})->name('posts');*/
Route::middleware(['auth:sanctum', 'verified'])->get('/posts', [PostController::class, 'showPosts'])->name('post');
Route::middleware(['auth:sanctum', 'verified'])->post('/posts/add_post', [PostController::class, 'addPost']);

Route::middleware(['auth:sanctum', 'verified'])->get('/my_feed', function () {
    return view('my_feed');
})->name('my_feed');

Route::get('/order_confirmation/{id}', [OrderController::class, 'orderConfirmation']);


Route::get('/biz-location/search', [BizController::class, 'searchLocation']);
Route::get('/location/search', [LocationController::class, 'searchLocation']);
Route::get('/location/children/{location_id}', [LocationController::class, 'getChildren']);
Route::get('/location/states/{country_code}', [LocationController::class, 'getStates']);

Route::get('/location/children/{location_id}', [LocationController::class, 'getChildren']);
Route::get('/location/states/{country_code}', [LocationController::class, 'getStates']);

/*Route::middleware(['auth:sanctum', 'verified'])->get('/cart', [CartController::class, 'showCart'])->name('cart');*/

Route::get('/cart', [CartController::class, 'showCart'])->name('new_cart');


Route::post('cart/remove', [CartController::class,'removeCart']);

Route::middleware(['auth:sanctum', 'verified'])->get('/my-travel-plans', [MyTravelPlansController::class, 'show_travel_plan'])->name('my-travel-plan');
Route::post('my-travel-plans/add_travel_plan', [MyTravelPlansController::class,'addTravelPlan']);
Route::get('my-travel-plans/delete/{id}',[MyTravelPlansController::class,'delete_travelPlan']);

Route::get('/biz-search',[BizController::class,'showSearch']);

Route::get('/order/{id}', [OrderController::class, 'showOrders']);
/*Route::middleware(['auth:sanctum', 'verified'])->post('/save_orders', [OrderController::class,'saveOrders']);*/

Route::get('/save_guest_orders', [OrderController::class,'saveOrders']);
Route::middleware(['auth:sanctum', 'verified'])->get('/save_shoppers_orders', [OrderController::class,'saveOrders']);

Route::middleware(['auth:sanctum', 'verified'])->get('/biz_owner/dashboard', [BizController::class, 'showDashboard'])->name('business-owner-dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/biz_owner/contacts', function () {
    return view('/biz_owner/contacts');
})->name('business-owner-contacts');

Route::middleware(['auth:sanctum', 'verified'])->get('/biz_owner/feed', function () {
    return view('/biz_owner/feed');
})->name('business-owner-feed');

Route::middleware(['auth:sanctum', 'verified'])->get('/biz_owner/suppliers', function () {
    return view('/biz_owner/suppliers');
})->name('business-owner-suppliers');

Route::middleware(['auth:sanctum', 'verified'])->get('/biz_owner/orders', function () {
    return view('/biz_owner/orders');
})->name('business-owner-orders');

Route::middleware(['auth:sanctum', 'verified'])->get('/biz_owner/sales', [OrderController::class, 'showSales'])->name('business-owner-sales-history');

Route::get('/', [HomeController::class, 'show_count']);

Route::get('/business-order', [OrderController::class,'showBusinessOrders']);

Route::get('/demo', function () {
        return view('demo');
});

Route::get('/search',[UserController::class,'search']);
Route::get('/sendrequest',[UserController::class,'sendrequest']);

Route::get('/business_records',[UserController::class,'getBusinessRecords']);
Route::get('/business_few_records',[UserController::class,'getFewBusinessRecords']);

/*Route::post('/biz-registration',[BizController::class,'ssssss']);*/

Route::get('/suggested_contacts',[UserController::class,'getSuggestedContacts']);
Route::get('/suggested_few_contacts',[UserController::class,'getFewSuggestedContacts']);  

Route::get('/get_contact_count',[UserController::class,'geContactCount']);

Route::get('/notification_details',[UserController::class,'getNotificationDetails']);


Route::get('/accept_contact_request',[UserController::class,'AcceptContactRequest']);

Route::get('/get_currency',[UserController::class,'getCurrency']);

Route::middleware(['auth:sanctum', 'verified'])->get('/old_contacts', [ContactController::class, 'show_old_contact'])->name('contact');

Route::get('business-contacts', [BizController::class,'show_BizContact']);

Route::get('/accepted_contacts', [UserController::class,'getAcceptedContacts']);
Route::get('/product/search', [ProductController::class, 'searchProduct']);
Route::get('/search_result', [ProductController::class, 'searchResult'])->name('search_result');;

Route::middleware(['auth:sanctum', 'verified'])->get('/search-results', function () {
    return view('search-results');
})->name('search-results');

Route::post('register', [UserController::class,'register']);
Route::post('user_register', [UserController::class,'user_register']);
Route::get('/thank-you-shopper', [UserController::class, 'thank_you_shopper']);

Route::get('check_emailaddress', [UserController::class,'check_emailaddress']);
Route::get('check_email_availability', [UserController::class,'check_email_availability']);

Route::get('save_business_personal_data', [BizController::class,'save_business_personal_data']);
Route::match(['get','post'],'save_product_data', [BizController::class,'save_product_data']);
Route::match(['get','post'],'save_video_data', [BizController::class,'save_video_data']);


Route::match(['get','post'],'update_product_data', [BizController::class,'update_product_data']);
Route::post('/biz-profile/change_tab_session', [BizController::class,'change_tab_session']);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/biz-registration.blade.php
@extends('layouts.my-town-app')
@push('head')
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">  
<script src="//code.jquery.com/jquery-1.12.1.js"></script>  
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>  

<script>
$(function(){
    $("#location_search").autocomplete({
      source :function( request, response ) {
        $.ajax({
           url: "{{ url('/location/search') }}",
           dataType: "json",
           data: {
              q: request.term 
           },
           success: function( data ) {
               response($.map(data.predictions, function(item) {
                     return {
                         label : item.description,
                         value : item.place_id
                     };
               }));
           }
        });
       },
       select: function (event, ui) {
             $("#location_search").val(ui.item.label);
             $("#place_id").val(ui.item.value);
             return false;
       }
   });
});

</script>
<style>
.ui-autocomplete-loading { background:url('/images/loading.gif') no-repeat right center }
</style>
@endpush
@section('content')
<div class="greybg content-box">
    <div class="container">
        <div class="row paddingbottom3">
            <div class="col-8 col-12-medium">
                <div class="whitebg margintop3">
                    <div class="wrapper">
                    <div class="title">
					    @php
					        $referer = request()->headers->get('referer');
					    @endphp
					    @if(preg_match('/register\?biz=1/',$referer))
					        {{ __('Step 2: ') }}
					    @endif
					    Let us create profile of your business
                    </div>
                    <form class="form" action='biz-registration' method="POST" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        <div class="input_field">
                            <label>Address</label>
                            <input type="text" class="input1" id="location_search" name="location_search" value="" placeholder="Address of your business">
                            <input type="hidden" id="place_id" name="place_id" value="" />
                        </div>
                        <div class="input_field">
                            <label>Name</label>
                            <input type="text" class="input1" id="name" name="name" placeholder="Name of your business" autocomplete="off">
                        </div>
                        <div class="input_field">
                            <label>Phone number</label>
                            <input type="text" class="input1" id="phone_number1" name="phone_number1" placeholder= "Phone number of your business" autocomplete="off">
                        </div>
                        <div class="input_field">
                            <label>Phone number2</label>
                            <input type="text" class="input1" id="phone_number2" name="phone_number2" placeholder="Another phone number of your business" autocomplete="off">
                        </div>
                        <div class="input_field">
                            <label>Email address</label>
                            <input type="email" class="input1" id="email_address" name="email_address" placeholder="Email address of your business" autocomplete="off">
                        </div>
                        <div class="input_field">
                            <label>Logo</label>
                            <input type="file" class="input1" id="logo" name="logo" placeholder="Add your company logo" autocomplete="off">
                        </div>
                        <div class="input_field">
                            <label>Banner Image</label>
                            <input type="file" class="input1" id="banner_image" placeholder="Add banner image for your business profile" name="banner_image">
                        </div>
                        <div class="input_field">
                            <label>Description</label>
                            <textarea class="textarea" id="description" placeholder="Add short description about your business" name="description"></textarea>
                        </div>
                        <div class="input_field">
                            <button type="submit" class="btn">Submit</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
            <div class="col-4 col-12-medium">
                <div class="whitebg padding2 margintop3">
                    <h5>4 Visitors also viewing this</h5>
                    <div class="orange">
                        <ul>
                            <li>Pratiksha</li>
                            <li>John Doe</li>
                        </ul>
                    </div>
                </div>
                <div class="whitebg padding2 margintop2">
                    <h5>4 Visitors also viewing this</h5>
                    <div class="orange">
                        <ul>
                            <li>Pratiksha</li>
                            <li>John Doe</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/businesess.blade.php
@push('head')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://kit.fontawesome.com/e3dc723f7b.js" crossorigin="anonymous"></script>
<script>
    $(document).ready( function () {
    $('#business').DataTable();
} );
</script>
@endpush

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Businesess') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">

		<div class="p-6 sm:px-20 bg-white border-b border-gray-200">
		<div class="mt-6 text-gray-900">
		<div class="table-responsive">
        <table id="business" class="display">
            <thead>
                <tr>
                    <th>NAME</th>
                    <th>COUNTRY</th>
                    <th>STATE PROVINCE</th>
                    <th>TOWN</th>   
                    <th>STREET ADDRESS 1</th>   
                    <th>STREET ADDRESS 2</th>
                    <th>PHONE NUMBER 1</th>
                    <th>PHONE NUMBER 2</th>
                    <th>EMAIL</th>
                </tr>
            </thead>
            <tbody>
                @foreach($businesess as $business)
                <tr>
                    <td>{{ $business->name }}</td>
                    <td>{{ $business->country }}</td>
                    <td>{{ $business->state_province }}</td>
                    <td>{{ $business->town }}</td>
                    <td>{{ $business->street_address1 }}</td>
                    <td>{{ $business->street_address2 }}</td>
                    <td>{{ $business->phone_number1 }}</td>
                    <td>{{ $business->phone_number2 }}</td>
                    <td>{{ $business->email_address }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
		</div><!-- table-responsive -->
		</div><!-- mt-6 -->
		</div><!-- p-6 -->
    </div>
</div>
</div>
</x-app-layout>

resources/views/business-contacts.blade.php
@extends('layouts.my-town-app')
@section('content')
@push('head')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://kit.fontawesome.com/e3dc723f7b.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
    $('#businesses').DataTable( {
        "columnDefs": [{
            "targets":[4],
            "orderable":false,
             "className": 'dt-body-right'
        }]
    } );
} );
</script>
@endpush


<div class="greybg content-box">
    <div class="container">
        <div class="row paddingbottom3">
            <div class="col-8 col-12-medium">
                <div class="tabcontent" style="display:block;">
                    <div class="p-6 sm:px-20 bg-white border-b border-gray-200">                
		                <div class="mt-6 text-gray-900">
		                    <div class="table-responsive">
                                <table id="businesses" class="display">
                                    <thead>
                                        <tr>
                                            <th>NAME</th>
                                            <th>EMAIL</th>      
                                            <th>PHONE</th>
                                            <th>ADDRESS</th>
                                            <th>ACTIONS</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach(\Auth::user()->biz_contacts as $biz_contact)
                                        <tr>
                                            <td>{{ $biz_contact->business->name }}</td>
                                            <td>{{ $biz_contact->business->email_address }}</td>
                                            <td>{{ $biz_contact->business->phone_number1 }}</td>
                                            <td>{{ $biz_contact->business->address }}</td>
                                            <td><a href = "business-contacts/delete/{{$biz_contact->id}}"><i class="fas fa-trash-alt"></a></i></td> 
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div><!-- table-responsive -->
		                </div><!-- mt-6 -->
		            </div><!-- p-6 -->
                </div>   
            </div>

            <div class="col-4 col-12-medium">
                <div class="whitebg padding2 margintop3">
                    <h5>4 Visitors also viewing this</h5>
                    <div class="orange">
                        <ul>
                            <li>Pratiksha</li>
                            <li>John Doe</li>
                        </ul>
                    </div>
                </div>
                <div class="whitebg padding2 margintop2">
                    <h5>4 Visitors also viewing this</h5>
                    <div class="orange">
                        <ul>
                            <li>Pratiksha</li>
                            <li>John Doe</li>
                        </ul>
                    </div>
                </div>
            </div>   
        </div>
    </div>
</div>

@endsection

resources/views/my-travel-plans.blade.php
@extends('layouts.my-town-app')
@section('content')
@push('head')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://kit.fontawesome.com/e3dc723f7b.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
    $('#my_travel_plan').DataTable( {
        "columnDefs": [{
            "targets":[3],
            "orderable":false,
            "className": 'dt-body-right'
        }]
    } );
} );
</script>
@endpush
<script>
   $(document).ready(function(){
                $('#showTravelPlanForm').on('click',function(){
                    $('#travel-plan-box').show();
                });

                $('#hide_travel_plan_form').on('click',function(){
                    $('#travel-plan-box').hide();
                });
            });
</script>

<div class="box1" id="travel-plan-box">

    <div class="jumbotron"> 
        <div class="card">
            <label id="hide_travel_plan_form" class="close-btn fas fa-times"></label>
            <div class="card-body" >
                <h5 class="card-title">Travel Plan Details</h5>
                <form action="{{ url('my-travel-plans/add_travel_plan') }}" method="POST">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label">Date:</label>
                        <input type="date" class="form-control" id="date" name="date">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">From:</label>
                        <input type="text" class="form-control" id="from" name="from">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">To:</label>
                        <input type="text" class="form-control" id="to" name="to">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="greybg content-box">
    <div class="container">
        <div class="row paddingbottom3">
            <div class="col-8 col-12-medium">
                <div id="Tab1" class="tabcontent" style="display:block;">

                <label class="show-btn" id="showTravelPlanForm" ><i class="fa fa-plus" aria-hidden="true"></i></label>

                <div class="p-6 sm:px-20 bg-white border-b border-gray-200">                
		<div class="mt-6 text-gray-900">
		<div class="table-responsive">
        @if(!empty($my_travel_plans))
        <table id="my_travel_plan" class="display">
            <thead>
                <tr>
                    <th>DATE</th>
                    <th>FROM</th>      
                    <th>TO</th>
                    <th>ACTIONS</th>
                </tr>
            </thead>
            <tbody>
                @foreach($my_travel_plans as $my_travel_plan)
                <tr>
                    <td>{{ $my_travel_plan->date }}</td>
                    <td>{{ $my_travel_plan->from }}</td>
                    <td>{{ $my_travel_plan->to }}</td>
                    <td><a href = "my-travel-plans/delete/{{$my_travel_plan->id}}"><i class="fas fa-trash-alt"></a></i></td> 
                
                
                
                </tr>
                @endforeach
            </tbody>
            </table>
            @endif
		</div><!-- table-responsive -->
		</div><!-- mt-6 -->
		</div><!-- p-6 -->
           <p>&nbsp;</p>
                </div>
                <div id="Tab4" class="tabcontent">
                    <div class="row marginbottom1 padding-0">
                        <div class="col-6 col-12-medium">
                            <h3>Customer reviews</h3>
                        </div>
                        <div class="col-6 col-12-medium">
                            <div class="floatright"><span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                            </div>
                        </div>
                    </div>
                    <p class="text-muted">56 reviews</p>
                    <hr class="marginbottom2 margintop2">
                    <p>The best sweet shop in Kothrud. The food quality and taste is just beyond words. Absolute value for money. Anytime good for parties and occasion.</p>
                    <div class="marginbottom1"><img src="/images/profile-pic-review.jpg" width="36" height="36" alt="" class="marginright2 vmiddle"><span class="bolder">Amit Sharma</span></div>
                    <div class="text-muted"><span class="marginright2 small bolder">11 Likes</span><span class="marginright2 small bolder">3 Comments</span></div>
                    <div class="text-muted marginbottom1"><span class="marginright2 small bolder"><i class="far fa-thumbs-up marginright1"></i>Likes</span><span class="marginright2 small bolder"><i class="far fa-comment marginright1"></i>Comments</span></div>
                    <div class="row">
                        <div class="col-1"><img src="/images/profile-pic-review.jpg" width="36" height="36" alt="" class="marginright2 vmiddle"></div>
                        <div class="col-11 col-12-medium">
                            <textarea rows="1" placeholder="Write your comment" tabindex="1" width="100%"></textarea>
                        </div>
                    </div>
                    <hr class="marginbottom2 margintop2">
                </div>
            </div>
            <div class="col-4 col-12-medium">
                <div class="whitebg padding2 margintop3">
                    <h5>4 Visitors also viewing this</h5>
                    <div class="colored">
                        <ul>
                            <li>Pratiksha</li>
                            <li>John Doe</li>
                        </ul>
                    </div>
                </div>
                <div class="whitebg padding2 margintop2">
                    <h5><img src="/images/ad-300x250.jpg" width="300" height="250" alt=""/></h5>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/signup-thank-you.blade.php
@extends('layouts.my-town-app')

@section('content')
<div class="greybg content-box">
    <div class="container">
        <div class="row paddingbottom3">
            <div class="col-8 col-12-medium">
                <div id="Tab1" class="tabcontent" style="display:block;">
    				<h3>Thank you for signing up!</h3>
    				<p>Own a business? <a href="/biz-registration">Register your business</a> or continue as a <a href="/my_feed">Shopper</a>.</p>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/usermanagement.blade.php
@push('head')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://kit.fontawesome.com/e3dc723f7b.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
    $('#users').DataTable( {
        "columnDefs": [{
            "targets":[3],
            "orderable":false,
            "className":"text-right",
        }]
    } );
} );
</script>
@endpush

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('User Management') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">

		<div class="p-6 sm:px-20 bg-white border-b border-gray-200">
		<div class="mt-6 text-gray-900">
		<div class="table-responsive">
        <table id="users" class="display">
            <thead>
                <tr>
                    <th>NAME</th>
                    <th>EMAIL ADDRESS</th>
                    <th>PHONE #</th>
                    <th>TOWN</th>
                    <th>REGISTERED</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                <tr>
                    <td>{{ @$user->name }}</td>
                    <td>{{ @$user->email }}</td>
                    <td>{{ @$user->phone }}</td>
                    <td>
						@if(!empty($user->place)) 
						{{ $user->place }}
						@endif 
					</td>
                    <td>{{ @$user->created_at->toDateString() }}</td>
                    <td><i class="fas fa-edit"></i> <i class="fas fa-trash-alt"></i></td> 
                </tr>
                @endforeach
            </tbody>
        </table>
		</div><!-- table-responsive -->
		</div><!-- mt-6 -->
		</div><!-- p-6 -->
    </div>
</div>
</div>
</x-app-layout>